name: Foundry CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    name: Run Forge Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Install dependencies (lib/)
        run: forge install

      - name: Build contracts
        run: forge build

      - name: Run Forge tests (ignore script folder)
        run: forge test --no-match-path "script/**/*"
